site_name: Learn Innova Developer Platform

repo_url: https://github.com/innovait-dk/idp_learn
edit_uri: edit/main/docs/

markdown_extensions:
   - meta
   - admonition
   - attr_list
   - md_in_html
   - toc:
      permalink: true

extra_css:
   - stylesheets/extra.css

extra_javascript:
  - javascripts/clarity.js

plugins:
   - search
   - glightbox
   #- unused_files
  # - htmlproofer

theme:
   name: material
   language: en
   features:
      - navigation.tabs
      - navigation.footer
      - content.code.copy
      - content.action.edit
   favicon: media/favicon.ico
   logo: media/innova.png
   palette:
      primary: white
   font:
      code: Roboto Mono
     
nav:
- "Home" : "index.md"
- "Get Started" : 
   - "Setting up Visual Studio" : "gettingstarted/visualstudio.md"
   - "First application" : "guide/wizard.md"
- "Designer" : 
   - "Introduction to designer" : "guide/elements/designer.md"
   - "The process" : "guide/elements/concept.md"
   - "Overview of architecture elements" : "guide/elements/elements-overview.md"
- "Architecture elements" : 
   - "Database" : "guide/elements/database.md"
   - "Entity Framework" : "guide/elements/entityframework.md"
   - "Validation" : "guide/elements/validation.md"
   - "Resx" : "guide/elements/resx.md"
   - "Resx Syncing EntityCaptions" : "guide/elements/captions.md"
   - "User Interface" : "guide/elements/wpf-ui.md"
   - "AppSettings" : "guide/elements/appsettings.md"
   - "UserSettings" : "guide/elements/usersettings.md"
   - "Revision" : "guide/elements/revision.md"
   - "Security" : "guide/elements/security.md"
   
- "How-To-Guides" : 
   - "How to customize" :
      - "Partial classes" : "tutorials/index.md"
      - "Code Tasks - Configuration" : "tutorials/CodeTasksConfiguration.md"
      - "Code Tasks - Customization" : "tutorials/CodeTasksCustomization.md"
   - "Entity Framework" : 
      - "Entity" : "tutorials/Entity/Entity.md"
      - "Entity Factory" : "tutorials/Entity/EntityFactory.md"
      - "Entity Security" : "tutorials/Entity/EntitySecurity.md"
      - "QueryModifier" : "tutorials/Entity/querymodifier.md"
   - "Validation" : 
      - "Basic" : "tutorials/Validation/validation.md"
      - "Other examples" : "tutorials/Validation/custom-validation.md"
   - "User Interface" :
      - "Mapper - Custom data-Property" : "tutorials/UI/Mapper.md"
      - "Mapper - Custom List-Property" : "tutorials/UI/Mapper-Template.md"
      - "View - Custom Show" : "tutorials/custom-show-view.md"
      - "Custom-Control on a field" : "tutorials/custom-control-on-one-field.md"
      - "ListView - Custom property" : "tutorials/custom-field-on-list.md"
      - "Customize control relation" : "tutorials/custom-control-relation.md"
      - "Grouping of fields" : "tutorials/UI/UiDesigner.md"
      - "File upload" : 
         - "File upload" : "tutorials/fileupload/index.md"
         - "1 field (bytes)" : "tutorials/fileupload/1-field.md"
         - "2 fields (bytes and filename)" : "tutorials/fileupload/2-fields.md"
         - "3 fields (bytes, filename and thumbnail)" : "tutorials/fileupload/3-fields.md"
         - "Other configurations" : "tutorials/fileupload/other-configurations.md"
      - "Dropdown with 'add-new' functionality" : "tutorials/dropdown-with-add.md"
      - "Customize insert and update logic" : "tutorials/Custom-insert-og-update-logic.md"
      - "Menu" :
         - "Add Menu" : "tutorials/UI/add-menubutton.md"
         - "MenuService" : "tutorials/UI/menuservice.md"
      - "Search" :
         - "Create quickfind" : "tutorials/add-quickfind.md"
         - "Search" : "tutorials/search.md"
   - "App and UserSettings" : "tutorials/Settings/settings.md"
   - "Logging" :
      - "Log in the application" : "tutorials/Logging/log_application.md"
      - "Use of NLog" : "tutorials/Logging/nlog.md"
   - "Contribute to the documentation" : "gettingstarted/contribution.md"
   - "Other frameworks" : "gettingstarted/otherframeworks.md"
- "Background" :
    - "The idea behind" : "guide/need.md"
    - "The vision" : "guide/intro.md"
    - "The product" : "guide/product.md"
    - "The process" : "guide/process.md"
    - "Videos" : "guide/playlist.md"
- "Contact" : "contact.md"